#yolo push

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,5 +1,5 @@
 # #!/usr/bin/env bash
-touch $1/fohr_andrew.pem
+# touch $1/fohr_andrew.pem
 
 echo "       Creating pem"
 echo "-----BEGIN RSA PRIVATE KEY-----" >> $1/fohr_andrew.pem
@@ -11,10 +11,10 @@ echo "       Created pem"
 pem=$1/fohr_andrew.pem
 minimum_size=1000
 
-# if [ $minimum_size -ge $(wc -c <"$pem") ]; then
-# 	echo "       pem error -- value not written to file"
-# 	exit 1
-# fi
+if [ $minimum_size -ge $(wc -c <"$pem") ]; then
+	echo "       pem error -- value not written to file"
+	exit 1
+fi
 
 if ! [ -f $1/fohr_andrew.pem ]; then
 	echo "       Missing fohr_andrew.pem"
