#yolo push

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,24 +1,16 @@
 # #!/usr/bin/env bash
-# # bin/compile <build-dir> <cache-dir> <env-dir>
 
-# ### Configure environment
+echo "-----> Found a redis.arm"
+echo "-----BEGIN RSA PRIVATE KEY-----" >> $1/fohr_andrew.pem
+cat $1/redis.arm >> $1/fohr_andrew.pem
+echo "" >> $1/fohr_andrew.pem
+echo "-----END RSA PRIVATE KEY-----" >> $1/fohr_andrew.pem
 
-# set -o errexit    # always exit on error
-# set -o pipefail   # don't ignore exit codes when piping output
-# set -o nounset    # fail on unset variables
+touch $1/fohr_andrew.pem
 
-# ### Configure directories
-
-# BUILD_DIR=${1:-}
-# CACHE_DIR=${2:-}
-# ENV_DIR=${3:-}
-# BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
-
-# mkdir -p "$BUILD_DIR/.heroku/autossh"
-# mkdir -p "$CACHE_DIR/autossh"
-
-# cd $BUILD_DIR
-
-# ### Copy profiles
+if ! [ -f $1/fohr_andrew.pem ]; then
+	echo "       Missing fohr_andrew.pem"
+	exit 1
+fi
 
 apt-get install autossh
